const DRAWING_TOOLS = {
  "en": [
    { id: 'line', name: 'Line', description: 'Draw a trend line' },
    { id: 'trend-line', name: 'Trend line', description: 'Draw a trend line' },
    { id: 'horizontal-line', name: 'Horizontal line', description: 'Draw a horizontal support/resistance line' },
    { id: 'vertical-line', name: 'Vertical line', description: 'Draw a time marker line' },
    { id: 'ray', name: 'Ray', description: 'Draw an infinitely extended ray' },
    { id: 'arrow', name: 'Arrow', description: 'Draw a marker arrow' },
    { id: 'extended-line', name: 'Extended line', description: 'Draw an extended line' },
    { id: 'parallel-channel', name: 'Parallel channel', description: 'Draw parallel channels' },
    { id: 'fibonacci-retracement', name: 'Fibonacci Retracement', description: 'Draws Fibonacci Retracement levels' },
    { id: 'fibonacci-extension', name: 'Fibonacci Extension', description: 'Draws Fibonacci Extension levels' },
    { id: 'fibonacci-time-zones', name: 'Fibonacci Time Zones', description: 'Draws Fibonacci Time Zones' },
    { id: 'fibonacci-circle', name: 'Fibonacci Circle', description: 'Draws Fibonacci Circle' },
    { id: 'fibonacci-spiral', name: 'Fibonacci Spiral', description: 'Draws Fibonacci Spiral' },
    { id: 'pitchfork', name: 'Andrew Pitchfork', description: 'Draws Andrew Pitchfork' },
    { id: 'schiff-pitchfork', name: 'Schiff Pitchfork', description: 'Draws a Schiff Pitchfork' },
    { id: 'quadrant-lines', name: 'Quadrant Lines', description: 'Draw price quadrant lines' },
    { id: 'balloon', name: 'Balloon Annotation', description: 'Add a balloon annotation' },
    { id: 'rectangle', name: 'Rectangle', description: 'Draw a rectangular area' },
    { id: 'ellipse', name: 'Ellipse', description: 'Draw an elliptical area' },
    { id: 'triangle', name: 'Triangle', description: 'Draw a triangle mode' },
    { id: 'polygon', name: 'Polygon', description: 'Draw a custom polygon' },
    { id: 'brush', name: 'Brush', description: 'Freehand drawing mode' },
    { id: 'callout', name: 'Callout', description: 'Add a text callout' },
    { id: 'text', name: 'Text', description: 'Add a text annotation' },
    { id: 'measure', name: 'Measurement tool', description: 'Measure price distances and time intervals' },
    { id: 'cross-line', name: 'Crosshair', description: 'Show crosshairs' },
    { id: 'date-range', name: 'Date range', description: 'Mark a date range' },
    { id: 'price-range', name: 'Price range', description: 'Mark a price range' },
    { id: 'projection', name: 'Price prediction', description: 'Trend-based price prediction' },
    { id: 'gann-box', name: 'Gann box', description: 'Draw Gann analysis tool' },
    { id: 'gann-fan', name: 'Gann Fan', description: 'Draw Gann Fan' },
    { id: 'gann-grid', name: 'Gann Grid', description: 'Draw a Gann Grid' },
    { id: 'speed-lines', name: 'Speed ​​Lines', description: 'Draw speed resistance lines' },
    { id: 'cycle-lines', name: 'Cycle Lines', description: 'Draw time cycle lines' },
    { id: 'time-cycles', name: 'Time Cycles', description: 'Mark time cycles' },
  ],
  "zhCN": [
    { id: 'line', name: '直线', description: '绘制趋势线' },
    { id: 'trend-line', name: '趋势线', description: '绘制趋势线' },
    { id: 'horizontal-line', name: '水平线', description: '绘制水平支撑/阻力线' },
    { id: 'vertical-line', name: '垂直线', description: '绘制时间标记线' },
    { id: 'ray', name: '射线', description: '绘制无限延伸的射线' },
    { id: 'arrow', name: '箭头', description: '绘制标记箭头' },
    { id: 'extended-line', name: '延长线', description: '绘制延长线' },
    { id: 'parallel-channel', name: '平行通道', description: '绘制平行通道' },
    { id: 'fibonacci-retracement', name: '斐波那契回撤', description: '绘制斐波那契回撤水平' },
    { id: 'fibonacci-extension', name: '斐波那契扩展', description: '绘制斐波那契扩展水平' },
    { id: 'fibonacci-time-zones', name: '斐波那契时间区间', description: '绘制斐波那契时间区间' },
    { id: 'fibonacci-circle', name: '斐波那契圆', description: '绘制斐波那契圆' },
    { id: 'fibonacci-spiral', name: '斐波那契螺旋', description: '绘制斐波那契螺旋' },
    { id: 'pitchfork', name: '安德鲁分叉线', description: '绘制安德鲁分叉线' },
    { id: 'schiff-pitchfork', name: 'Schiff分叉线', description: '绘制Schiff分叉线' },
    { id: 'quadrant-lines', name: '象限线', description: '绘制价格象限线' },
    { id: 'balloon', name: '气球标注', description: '添加气球标注' },
    { id: 'rectangle', name: '矩形', description: '绘制矩形区域' },
    { id: 'ellipse', name: '椭圆', description: '绘制椭圆区域' },
    { id: 'triangle', name: '三角形', description: '绘制三角形模式' },
    { id: 'polygon', name: '多边形', description: '绘制自定义多边形' },
    { id: 'brush', name: '画笔', description: '自由绘制模式' },
    { id: 'callout', name: '标注', description: '添加文字标注' },
    { id: 'text', name: '文本', description: '添加文本注释' },
    { id: 'measure', name: '测量工具', description: '测量价格距离和时间间隔' },
    { id: 'cross-line', name: '十字线', description: '显示十字准星' },
    { id: 'date-range', name: '日期范围', description: '标记日期范围' },
    { id: 'price-range', name: '价格范围', description: '标记价格范围' },
    { id: 'projection', name: '价格预测', description: '基于趋势的价格预测' },
    { id: 'gann-box', name: '江恩箱', description: '绘制江恩分析工具' },
    { id: 'gann-fan', name: '江恩扇形线', description: '绘制江恩扇形线' },
    { id: 'gann-grid', name: '江恩网格', description: '绘制江恩网格' },
    { id: 'speed-lines', name: '速度线', description: '绘制速度阻力线' },
    { id: 'cycle-lines', name: '周期线', description: '绘制时间周期线' },
    { id: 'time-cycles', name: '时间周期', description: '标记时间周期' },
  ]
}

export { }