import { I18n } from '../../i18n';

export interface EmojiCategory {
    id: string;
    name: string;
}

export interface EmojiItem {
    character: string;
    name: string;
    category: string;
}

export const getEmojiCategories = (i18n: I18n): EmojiCategory[] => [
    { id: 'smileys', name: i18n.t('emojiSmileys') },
    { id: 'people', name: i18n.t('emojiPeople') },
    { id: 'animals', name: i18n.t('emojiAnimals') },
    { id: 'food', name: i18n.t('emojiFood') },
    { id: 'activities', name: i18n.t('emojiActivities') },
    { id: 'travel', name: i18n.t('emojiTravel') },
    { id: 'objects', name: i18n.t('emojiObjects') },
    { id: 'symbols', name: i18n.t('emojiSymbols') },
    { id: 'flags', name: i18n.t('emojiFlags') },
];

export const EMOJI_LIST: EmojiItem[] = [
    { character: '😀', name: '笑脸', category: 'smileys' },
    { character: '😃', name: '大笑', category: 'smileys' },
    { character: '😄', name: '微笑', category: 'smileys' },
    { character: '😁', name: '笑嘻嘻', category: 'smileys' },
    { character: '😆', name: '哈哈笑', category: 'smileys' },
    { character: '😅', name: '流汗笑', category: 'smileys' },
    { character: '😂', name: '笑哭', category: 'smileys' },
    { character: '🤣', name: '打滚笑', category: 'smileys' },
    { character: '😊', name: '微笑脸', category: 'smileys' },
    { character: '😇', name: '天使', category: 'smileys' },
    { character: '🙂', name: '微微笑', category: 'smileys' },
    { character: '🙃', name: '倒脸', category: 'smileys' },
    { character: '😉', name: '眨眼', category: 'smileys' },
    { character: '😍', name: '爱心眼', category: 'smileys' },
    { character: '🥰', name: '微笑爱心', category: 'smileys' },
    { character: '😘', name: '飞吻', category: 'smileys' },
    { character: '😋', name: '美味', category: 'smileys' },
    { character: '😎', name: '墨镜', category: 'smileys' },
    { character: '🤩', name: '星星眼', category: 'smileys' },
    { character: '🥳', name: '派对', category: 'smileys' },
    { character: '😏', name: '得意', category: 'smileys' },
    { character: '😢', name: '哭泣', category: 'smileys' },
    { character: '😭', name: '大哭', category: 'smileys' },
    { character: '😡', name: '愤怒', category: 'smileys' },
    { character: '🤯', name: '爆炸头', category: 'smileys' },
    { character: '🥺', name: '恳求脸', category: 'smileys' },
    { character: '😱', name: '尖叫', category: 'smileys' },
    { character: '🤔', name: '思考', category: 'smileys' },
    { character: '😴', name: '睡觉', category: 'smileys' },
    { character: '😷', name: '口罩', category: 'smileys' },
    { character: '🤒', name: '生病', category: 'smileys' },
    { character: '🤕', name: '受伤', category: 'smileys' },
    { character: '🥶', name: '冷脸', category: 'smileys' },
    { character: '🥵', name: '热脸', category: 'smileys' },
    { character: '😈', name: '小恶魔', category: 'smileys' },
    { character: '👿', name: '恶魔', category: 'smileys' },
    { character: '💀', name: '骷髅', category: 'smileys' },
    { character: '👻', name: '鬼魂', category: 'smileys' },
    { character: '👽', name: '外星人', category: 'smileys' },
    { character: '🤖', name: '机器人', category: 'smileys' },
    { character: '👶', name: '婴儿', category: 'people' },
    { character: '👧', name: '女孩', category: 'people' },
    { character: '👦', name: '男孩', category: 'people' },
    { character: '👩', name: '女人', category: 'people' },
    { character: '👨', name: '男人', category: 'people' },
    { character: '👵', name: '老奶奶', category: 'people' },
    { character: '👴', name: '老爷爷', category: 'people' },
    { character: '🐵', name: '猴脸', category: 'animals' },
    { character: '🐒', name: '猴子', category: 'animals' },
    { character: '🐶', name: '狗脸', category: 'animals' },
    { character: '🐕', name: '狗', category: 'animals' },
    { character: '🐩', name: '贵宾犬', category: 'animals' },
    { character: '🐺', name: '狼', category: 'animals' },
    { character: '🦊', name: '狐狸', category: 'animals' },
    { character: '🐱', name: '猫脸', category: 'animals' },
    { character: '🐈', name: '猫', category: 'animals' },
    { character: '🦁', name: '狮子', category: 'animals' },
    { character: '🐯', name: '老虎脸', category: 'animals' },
    { character: '🐴', name: '马脸', category: 'animals' },
    { character: '🦄', name: '独角兽', category: 'animals' },
    { character: '🦓', name: '斑马', category: 'animals' },
    { character: '🐮', name: '牛脸', category: 'animals' },
    { character: '🐷', name: '猪脸', category: 'animals' },
    { character: '🐭', name: '老鼠脸', category: 'animals' },
    { character: '🐹', name: '仓鼠', category: 'animals' },
    { character: '🐰', name: '兔子脸', category: 'animals' },
    { character: '🐻', name: '熊', category: 'animals' },
    { character: '🐨', name: '考拉', category: 'animals' },
    { character: '🐼', name: '熊猫', category: 'animals' },
    { character: '🐔', name: '鸡', category: 'animals' },
    { character: '🐦', name: '鸟', category: 'animals' },
    { character: '🐧', name: '企鹅', category: 'animals' },
    { character: '🦅', name: '鹰', category: 'animals' },
    { character: '🦆', name: '鸭', category: 'animals' },
    { character: '🦉', name: '猫头鹰', category: 'animals' },
    { character: '🦇', name: '蝙蝠', category: 'animals' },
    { character: '🐸', name: '青蛙', category: 'animals' },
    { character: '🐢', name: '乌龟', category: 'animals' },
    { character: '🐍', name: '蛇', category: 'animals' },
    { character: '🍎', name: '红苹果', category: 'food' },
    { character: '🍐', name: '梨', category: 'food' },
    { character: '🍊', name: '橙子', category: 'food' },
    { character: '🍋', name: '柠檬', category: 'food' },
    { character: '🍌', name: '香蕉', category: 'food' },
    { character: '🍉', name: '西瓜', category: 'food' },
    { character: '🍇', name: '葡萄', category: 'food' },
    { character: '🍓', name: '草莓', category: 'food' },
    { character: '🍑', name: '桃子', category: 'food' },
    { character: '🍍', name: '菠萝', category: 'food' },
    { character: '⚽', name: '足球', category: 'activities' },
    { character: '🏀', name: '篮球', category: 'activities' },
    { character: '🏈', name: '美式足球', category: 'activities' },
    { character: '⚾', name: '棒球', category: 'activities' },
    { character: '🎾', name: '网球', category: 'activities' },
    { character: '🏐', name: '排球', category: 'activities' },
    { character: '🎱', name: '台球', category: 'activities' },
    { character: '🏓', name: '乒乓球', category: 'activities' },
    { character: '🏸', name: '羽毛球', category: 'activities' },
    { character: '🚗', name: '汽车', category: 'travel' },
    { character: '🚕', name: '出租车', category: 'travel' },
    { character: '🚙', name: 'SUV', category: 'travel' },
    { character: '🚌', name: '巴士', category: 'travel' },
    { character: '🚎', name: '电车', category: 'travel' },
    { character: '🏎️', name: '赛车', category: 'travel' },
    { character: '🚓', name: '警车', category: 'travel' },
    { character: '⌚', name: '手表', category: 'objects' },
    { character: '📱', name: '手机', category: 'objects' },
    { character: '📲', name: '手机箭头', category: 'objects' },
    { character: '💻', name: '笔记本电脑', category: 'objects' },
    { character: '⌨️', name: '键盘', category: 'objects' },
    { character: '🖥️', name: '台式电脑', category: 'objects' },
    { character: '❤️', name: '红心', category: 'symbols' },
    { character: '🧡', name: '橙心', category: 'symbols' },
    { character: '💛', name: '黄心', category: 'symbols' },
    { character: '💚', name: '绿心', category: 'symbols' },
    { character: '💙', name: '蓝心', category: 'symbols' },
    { character: '💜', name: '紫心', category: 'symbols' },
    { character: '🖤', name: '黑心', category: 'symbols' },
    { character: '💔', name: '破碎的心', category: 'symbols' },
    { character: '🏁', name: '方格旗', category: 'flags' },
    { character: '🚩', name: '三角旗', category: 'flags' },
    { character: '🎌', name: '交叉旗', category: 'flags' },
    { character: '🏴', name: '黑旗', category: 'flags' },
    { character: '🏳️', name: '白旗', category: 'flags' },
    { character: '🇨🇳', name: '中国', category: 'flags' },
    { character: '🇺🇸', name: '美国', category: 'flags' },
    { character: '🇯🇵', name: '日本', category: 'flags' },
    { character: '🇰🇷', name: '韩国', category: 'flags' },
    { character: '🇬🇧', name: '英国', category: 'flags' },
];

export interface EmojiProperties {
    emoji: string;
    fontSize: number;
    id: string;
}

export const createDefaultEmojiProperties = (): EmojiProperties => ({
    emoji: '😀',
    fontSize: 24,
    id: `emoji_${Date.now()}`
});